name: Deploy Blazor WebAssembly to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

permissions:
  contents: write  # Needed to push to the gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Publish Blazor WebAssembly project
        run: dotnet publish GTS.AppWeb/GTS.AppWeb.csproj -c Release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./GTS.AppWeb/bin/Release/net9.0/publish/wwwroot/GuessTheSender
          publish_branch: gh-pages
